### ISSUE TITLE
Checkin feature

### ISSUE THREAD

**Issue by mzafarr** [ahadsts9901/smit-b9-final-hackathon#1]
AOA, I wanted to ask where the 100meter feature implemented that the student cannot check-in without being within 100meter range of a certain place. 

You can remove this issue after answering. Thanks.

**Comment by ahadsts9901** [comment]
W.salam.....Here is the easy guide for you with the folder structure

web/src/components/Modal/Modal.jsx

Line number 19 to 127.......there is a full function of checkin you can see
it.
